version: '3'
services:
  vaccinator:
    container_name: vaccinator
    build: .
    ports: 
      - 8080:8080
    volumes:
      - api:/usr/src/app/
    depends_on: 
      postgres:
        condition: service_healthy
    networks:
      - vaccinator
    labels:
      kompose.service.type: LoadBalancer


  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}  
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_HOST: ${DB_HOST}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - database_postgres:/var/lib/postgresql/data/pgdata
    networks:
      - vaccinator
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "5050:80"
    networks:
      - vaccinator
    restart: unless-stopped


volumes:
  api:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  vaccinator:
    driver: bridge
